### ISSUE TITLE
eventmaker

### ISSUE THREAD

**Issue by The-Real-Ketchum-Dev** [palmtree5/palmtree5-cogs#16]
Thank you for taking the time to come report an issue. To help with this, please fill out the following info. Feel free to include screenshots of error messages as needed.

Cog: eventmaker

Description of the problem: seems like it isnt saving events that are created. also getting an error when trying to join an event the error says -----

Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python35\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\eventmaker\eventmaker.py", line 128, in event_join
    if not to_join["has_started"]:
TypeError: 'NoneType' object is not subscriptable

not quite sure how to even fix this

**Comment by palmtree5** [comment]
I can't reproduce this myself. Are you up to date?
