### ISSUE TITLE
hypixelapi error

### ISSUE THREAD

**Issue by Edgar06ka** [palmtree5/palmtree5-cogs#31]
Thank you for taking the time to come report an issue. To help with this, please fill out the following info. Feel free to include screenshots of error messages as needed.

Cog: 
hypixelapi
Description of the problem: 
error in command hypixel player
console log
[2019-07-21 17:50:01] [ERROR] red: Exception in command 'hypixel player'
Traceback (most recent call last):
  File "c:\users\edgar\appdata\local\programs\python\python37-32\scripts\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Edgar\AppData\Local\Red-DiscordBot\Red-DiscordBot2\cogs\CogManager\cogs\hpapi\hpapi.py", line 230, in hpplayer
    player = await self.api_client.player_from_name(name)
  File "C:\Users\Edgar\AppData\Local\Red-DiscordBot\Red-DiscordBot2\cogs\Downloader\lib\aiopixel\client.py", line 310, in player_from_name
    return await self.player_from_uuid(uuid)
  File "C:\Users\Edgar\AppData\Local\Red-DiscordBot\Red-DiscordBot2\cogs\Downloader\lib\aiopixel\client.py", line 350, in player_from_uuid
    player_stats.append(getattr(stats, k + "Stats")(v))
AttributeError: module 'aiopixel.models.stats' has no attribute 'PitStats'

**Comment by Vexed01** [comment]
I also have this error.

Manually installing `aiopixel==0.2.4` and/or `aoipixel` does not make this work (aiopixel==0.2.4 is a requirement in [`info.json`](https://github.com/palmtree5/palmtree5-cogs/blob/redv3-rewrites/hpapi/info.json)

My error is the same
Windows 10 Python 3.7.4
