### ISSUE TITLE
[hpapi]  Status code: 403.

### ISSUE THREAD

**Issue by DJTOMATO** [palmtree5/palmtree5-cogs#50]
Thank you for taking the time to come report an issue. To help with this, please fill out the following info. Feel free to include screenshots of error messages as needed.

Cog:  hpapi

Description of the problem: 

``` [2023-07-03 22:33:03] [ERROR] red: Exception in command 'hypixel player'
 Traceback (most recent call last):
   File "/home/glas/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
     ret = await coro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/hpapi/hpapi.py", line 240, in hpplayer
     player = await self.api_client.player_from_name(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/mnt/hdd/data/lenabot/cogs/Downloader/lib/aiopixel/client.py", line 310, in player_from_name
     return await self.player_from_uuid(uuid)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/mnt/hdd/data/lenabot/cogs/Downloader/lib/aiopixel/client.py", line 337, in player_from_uuid
     data = await self._request(
            ^^^^^^^^^^^^^^^^^^^^
   File "/mnt/hdd/data/lenabot/cogs/Downloader/lib/aiopixel/client.py", line 36, in _request
     raise PixelException(
 aiopixel.exceptions.PixelException: An error occurred while making the request.
 Status code: 403.
 Reason: Forbidden```

Apparently the API url was changed

**Comment by palmtree5** [comment]
403 status code means access is forbidden, usually due to an invalid API key. I would suggest trying to create a new API key via [their developer dashboard](https://developer.hypixel.net) (you will need an account on their forums in order to login, and once logged in, you will want to create an app for personal use which may take time for approval).
